# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: 3D Python Robotics
# site_url: need to create github page first and put it here

nav:
  - Home: 'index.md'
  - Documentation:
    - 'pyrc3d 🚗':
      - 'agent': 'pyrc3d_doc/agent/index.md'
      - 'sim': 'pyrc3d_doc/simulation/index.md'
      - 'sensors': 'pyrc3d_doc/sensors/index.md'
    - 'algorithms 🎮':
      - 'Mapping': 'algorithms_doc/mapping/index.md'
      - 'PathPlanning': 'algorithms_doc/path_planning/index.md'
      - 'Controllers': 'algorithms_doc/controllers/index.md'
    - 'utilities ⌚':
      - 'utils': 'utilities_doc/utils/index.md'
      - 'timings': 'utilities_doc/timings/index.md'

theme:
  name: material
  font:
    text: Source Sans Pro
    code: Source Code Pro
  features:
    - header.autohide
    - announce.dismiss
    - navigation.tabs
    - navigation.top
    - navigation.tabs.sticky
  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: custom_light_theme
      #toggle:
        #icon: material/brightness-7
        #name: Switch to dark mode

    #- media: "(prefers-color-scheme: dark)"
      #scheme: slate
      #toggle:
        #icon: material/brightness-4
        #name: Switch to light mode

markdown_extensions:
  - meta
  - md_in_html
  - def_list
  - attr_list
  - admonition
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.betterem
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.smartsymbols
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      use_pygments: true
      linenums: true
      linenums_style: table
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true

extra_css:
  - stylesheets/extra.css
        
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
